name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Chez Scheme
        run: sudo apt-get install chezscheme

      - name: Run all tests
        run: make test
